name: Build and Release Angular

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Change directory to front-admin
        working-directory: front-admin/app/front-admin
        run: |
          npm install
          npm run build --prod --output-path=dist/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: angular-app
          path: front-admin/app/front-admin/dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          files: front-admin/app/front-admin/dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
