name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar sshpass para comandos remotos
        run: sudo apt-get install sshpass

      - name: Desplegar en el servidor
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no -p "$SERVER_PORT" $SERVER_USER@$SERVER_IP "
            mkdir -p /temp-deploy-web &&
            git clone https://github.com/MatiasFAC/test-ga /temp-deploy-web &&
            cp -r /temp-deploy-web/web/* /apps/test-ga/web/ &&
            cd /apps/test-ga &&
            docker compose build &&
            docker compose up -d
          "
